### ISSUE TITLE
новые мелочи

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#1]
1. при самом первом запуске нету нуля - когда исправишь напиши в чём ошибка и как ты её нашёл
2. справа от вкладки run внизу есть вкладка problems - в идеале она должна быть пустой, у тебя их 21 (особенно удивительна последняя) - это то что тебе студия подчёркивает
3. про модификаторы доступа слышал? почему у тебя всё default?
4. у тебя как раз идеальный пример почему линеар лэйаут это плохо. сможешь объяснить почему?

**Comment by russabit** [comment]
5. так же снова не сделал описание (read me), посмотри как у меня в bsc сделано, скрины, описание, что делает (переворот, сохранение старого и т.п.)
6. кликлистенер для чисел у тебя вынесен отдельно - правильно, потому что он один сеттится всем числам и ты его переиспользуешь. кликлистенеры для операций сеттятся там же где и описываются. тебе уже можно начинать читать макконелла и бегло посмотреть что такое солид (первую букву с). тогда сможешь понять, что выделять в отдельные сущности нужно не только когда ты переиспользуешь (как кликлистенер для чисел), но и когда ты выполняешь разные вещи. в идеале одна строчка должна выполнять одну вещь и если ты вынесешь отдельно создание кликлистенера и отдельно его вешание на кнопку, то каждая операция будет отдельно. подумай что ещё можно отдельно вынести (подсказка - для чего нужны private методы)
7. где вообще используется secondaryField ? ты его только объявил и нашёл вьюху. он же вроде должен показывать твои два числа и операцию между ними
8. про автоформат слышал? всегда когда напишешь хоть одну строчку привыкай форматировать после этого Ctrl + Alt + L. Уж либо хотя бы перед пушем коммита, что бы если я нажимал у себя у меня ничего за тебя не форматировалось. 
9. так же есть такая веща как кодстайл - [java](https://skillbox.ru/media/base/java_code_style_kak_pravilno_oformlyat_kod_java/), [kotlin](https://habr.com/ru/company/redmadrobot/blog/343458/), это вообще как правописание, самые азы (как в прошлый раз у тебя метод был с большой буквы), прочитай обе ссылки и поправь всё
10. про то, что сеттить один и тот же кликлистенер для чисел можно одной операцией в цикле ты немного не додумал раз не нашёл способа или не понял - можно все кнопки собрать в список `ArrayList<Button> numButtons = new ArrayList<>(10);` и одной строчкой добавить один и тот же листенер для всех кнопок `        for (Button button : numButtons) {
            button.setOnClickListener(onCLNumber);
        }`
onCLNumber  кстати плохое название, см. пункт 9

не то, чтобы это обязательно, просто вариант на подумать и как потом организовывать код


поправляй сначала мелкие пункты и делай коммит на новой ветке issue_1 с внятным названием типа issue_1_fix_1_2_6_8 и делай пуллреквест, я должен буду его зааппрувить и тогда можно будет вливать в главную main ветку. обычно примерно так построена работа в команде, только вместо issue будут таски в jira со своими номерами.
остальные пункты посложнее и которые делать подольше делай потом другим ПР-ом таким же способом

**Comment by SkirdaD** [comment]
1. Ошибка была в том, что при первом запуске onStart давал null, т.к. подтягивал значение из SharedPreferences , а его там не было.  Исправил через проверку на содержимое в SP нужных данных.  Сначала сам догадался, а потом через дебагер подтвердилось. Не обращал на эту проблему, т.к. всегда просто его перезапускал.

2. Всё исправил. Переделал через лямбду все лисенеры. 
    Слово "Dima", я так понял, просто нет в словаре. Теперь есть.  
    И с switch cace были проблемы (Resource IDs will be non-final by default in Android Gradle Plugin version 8.0, avoid using  them in switch case statements). Почитал, пишут, что гугл советует через if/else, когда работаешь с R.id.

3. Слышал. Я не просто так его не написал. Поставил protected (по моему и private подходит). Хотя меня устраивал и дефолтный меня устраивал.  

4. Да, сейчас я понял, почему линеар лэйаут плох. Что бы разместить несколько кнопок, приходится добавлять кучу лэйаутов, что бы они стояли там, где надо. Нужно переделать?

**Comment by SkirdaD** [comment]
7. Нигде. Мы же с тобой решили, что пока не обязательно. Или сделать?

8. Первый раз слышу) Всё понял. Буду делать.

9. Всё прочитал. Ничего не исправил. Всё, вроде, уже правильно. Лисенер кнопок поправил.

**Comment by russabit** [comment]
отлично, тогда для поправленных делай ПР, про п.7 можешь сделать тоже раз уже начал, по п.4 переделай на констрейнт, так чтобы не было вложенных друг в друга лейаутов - это плохо для производительности, и когда переделаешь проверим сколько памяти будут жрать твои линеары и сколько памяти будет есть один констрейнт. 

по поводу п.1 насколько я бегло посмотрел у тебя дефортное значение в шаредах вторым аргументом стоит "", поэтому при первом запуске прилаги этот дефолт и берётся, нет?

если после прочтения кодстайлов ничего не исправил, то это плохо, читай ещё раз котлиновский. подсказка - какой порядок в структуре класса

**Comment by SkirdaD** [comment]
Да, я понял, что скорее всего ошибка в структуре проекта. Попробую еще раз разобраться.

по п1. Я не до конца понял конструкцию. Нарвался на видео, где, видимо, неправильно объяснено. В скобках в шаредах стоит ключ, а потом дефолтное значение? Если ничего в шареде не сохранено, то будет то, что стоит дальше) Тогда, да, всё просто получается. Спасибо, подсказал.

**Comment by SkirdaD** [comment]
Я нашел у себя еще одну ошибку)
При делении на ноль я обрабатывал АрифметикЭксепшн. Но изначально я написал код с Интами. 
А потом с дабл. Но при делении на 0, в случае с дабл, никакого исключения не будет.
Тоже переделал.

**Comment by SkirdaD** [comment]
9. Поправил последовательность методов.

**Comment by SkirdaD** [comment]
И, я так понял, что все переменные до onCreate нужно сделать статиком?

**Comment by SkirdaD** [comment]
6. Почитал СОЛИД. Ты ведешь к тому, что метод operation нужно разбить на несколько отдельных методов? Или вообще в разные классы?

**Comment by SkirdaD** [comment]
10. Именно до этой конструкции я и догадался. Честно)
 Но мне она показалась ничем не лучше, пока я не вспомнил, что можно сразу кучей добавить. До этого я каждый элемент добавлял отдельно и количество строк было еще больше, чем до этого.
Короче, я переделал с for-each.

**Comment by SkirdaD** [comment]
Что такое  jira ?
И почему мы не делаем сразу через него?

**Comment by SkirdaD** [comment]
Так, мне осталось ReadMe сделать, доп.экран, лэйаут сменить.

**Comment by SkirdaD** [comment]
мне readMe сделать у себя файлом или лучше на гитхабе? Скорее всего абсолютно всё равно)

**Comment by SkirdaD** [comment]
Хотя нет, только на гитхабе) Там расширение особенное

**Comment by SkirdaD** [comment]
Тогда пока не буду всё доделывать, а займусь новым коммитом. Буду разбираться. Не знаю, что такое пулреквест и работа с другой веткой.

**Comment by SkirdaD** [comment]
и еще вопрос. Вот это наше обсуждение кто-то видит или только мы?

**Comment by SkirdaD** [comment]
Короче) Что-то сделал. 
Создал ветку - сделал коммит - создал пулреквест (я так понял, что это сообщение всем разработчикам, что я что-то изменил). Дальше (не очень понимаю) ты это как-то одобришь и можно сделать слияние?
Смотри.

**Comment by SkirdaD** [comment]
Кстати, когда делал пулреквест у меня высветилось ошибки(проблемы) с xml файлом.

**Comment by SkirdaD** [comment]
5. Сделал ReadMe.

**Comment by russabit** [comment]
> И, я так понял, что все переменные до onCreate нужно сделать статиком?

почему и какой в этом смысл?

> ты это как-то одобришь и можно сделать слияние?

да как только поправишь те комменты, которые я написал в ПР-е

> 6\. Почитал СОЛИД. Ты ведешь к тому, что метод operation нужно разбить на несколько отдельных методов? Или вообще в разные классы?

да, это пока рановато и дальше сделаем отдельным ишью - там у тебя глаза откроются если правильно задачу тебе задам 

> Что такое jira ? И почему мы не делаем сразу через него?

да типа отдельного сайта для проекта где вместо ишью (issue здесь) кучи тасок (задач) с описаниями багов или фич и каждый берёт их на себя и трекает сколько времени потратил, открывает, закрывает и т.п.


> Хотя нет, только на гитхабе) Там расширение особенное

да наверное можно и в проекте создать файл .md и тогда он и в студии будет виден и для студии есть плагин чтобы файлы такого типа можно было редактировать

> и еще вопрос. Вот это наше обсуждение кто-то видит или только мы?

все видят но это и хорошо, никто читать не будет всё равно, главно что история сохранится на будущее и у тебя и у меня гитхаб зеленеет.

вообще молодец, исправляй комменты по ПР-у, смёржим и я открою новые отдельные ишью для следующих вещей

**Comment by russabit** [comment]
для истории - закрыли все пункты кроме первого, его выносим в отдельный ишью.

**Comment by SkirdaD** [comment]
Разве первого?
