### ISSUE TITLE
вынесение всех вью из активити во вьюхолдер

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#12]
сейчас у нас в активити огромная простыня текста относящаяся к поиску вьюшек (которые всё равно лежат в локальных переменных), вешанию на них кликлистенеров и доставания из них значений:

<img width="837" alt="Screenshot 2023-02-16 at 10 21 26 am" src="https://user-images.githubusercontent.com/50712640/219236890-6fde041a-0a48-4a50-a085-a77be125df4e.png">

есть такой паттерн вьюхолдер (используется в ресайлере обычно), но нам подойдёт его использование просто в активити, т.к. слишком много места занимает код с одним логическим смыслом - найти вьюхи и повесить на них КЛ-ы. ещё и это можно разделить на два метода.

**Comment by russabit** [comment]
задача - вынести этот код в отдельный класс MainActivityViewHolder который будет отвечать за хранение списка вьюшек для активити, так чтобы активити могла удобно в одном месте с ним работать. 

метафорично это как если у человека(аквивити) будет отдельный список кнопок и текствьюх в блокноте с их конкретным адресом, и когда человеку что-то надо с ними сделать, он сначала открывает блокнот и сразу берёт оттуда нужные адреса кнопок/вьюх (которые он уже в какой-то момент нашёл и написал как список - изначально вызвал ::найтиИпроинициализироватьВьюхи).

надо будет сделать это до изменения кликлистенеров, т.к. в кликлистенерах нам нужны будут как раз эти ссылки на вьюхи (`var = ExtensionMethods.getNum(mainTextView);` и `ExtensionMethods.setCalcData(mainTextView, calculatorData);`, чтобы обращаться к `mainTextView` не как к локальной переменной, а доставать из блокнота как `viewHolder.getMainTextView()` и потом передавать так в ::getNum и ::setCalcData

**Comment by SkirdaD** [comment]
Я вот что нашел:
1. https://developer.alexanderklimov.ru/android/listview/listview-perfomance.php
2. https://nurlandroid.com/?p=389

В эту сторону копать? Или не то?

**Comment by SkirdaD** [comment]
Сначала это, а потом фабрику? С фабрикой более понятно)

**Comment by russabit** [comment]
> Я вот что нашел:
> 
> 1. https://developer.alexanderklimov.ru/android/listview/listview-perfomance.php
> 2. https://nurlandroid.com/?p=389
> 
> В эту сторону копать? Или не то?

не надо ничего копать, тебя только запутают примеры

в них это относится к ЛистВью. Который устарел и все используют РесайклерВью. Который тоже устарел и все используют поверх него адаптер делегаты. Что тоже уже устаревает потому что вышел компоуз)) но в целом ВьюХолдер - это всего лишь паттерн, просто про него особо никто не пишет _не в контексте листвью/ресайклервью_

я тебе предлагаю просто вынести код, на который я сослался выше в отдельный класс, а вьюхолдер это название этого класса, потому что он будет держать в себе найденные ссылки на вьюхи, а активити в нужный момент будет к нему обращаться за вьюхами из списка. всё. пример как это будет использоваться я тебе уже написал в двух строчках кода в конце, они и есть подсказки.

**Comment by russabit** [comment]
> Сначала это, а потом фабрику? С фабрикой более понятно)

тебе ничего не мешает делать одновременно две или даже три ветки с пуллреквестами. будет даже эффективней

**Comment by SkirdaD** [comment]
> > Сначала это, а потом фабрику? С фабрикой более понятно)
> 
> тебе ничего не мешает делать одновременно две или даже три ветки с пуллреквестами. будет даже эффективней

Вот я в этом не сильно понимаю) 
Смотри, начальная база - это ветка мастер.
И я делаю две ветки. Например, мне и Антону.
Он что-то пишет и использует, например, переменные активити. А я в своей ветке делаю всё, чтобы убрать эти переменные. И я закончил быстрее, и ты влил мою ветку. 
И что дальше?

**Comment by SkirdaD** [comment]
Кстати...
public class ExtensionMethods
разве он должен быть пабликом?

**Comment by russabit** [comment]
> > > Сначала это, а потом фабрику? С фабрикой более понятно)
> > 
> > 
> > тебе ничего не мешает делать одновременно две или даже три ветки с пуллреквестами. будет даже эффективней
> 
> Вот я в этом не сильно понимаю) Смотри, начальная база - это ветка мастер. И я делаю две ветки. Например, мне и Антону. Он что-то пишет и использует, например, переменные активити. А я в своей ветке делаю всё, чтобы убрать эти переменные. И я закончил быстрее, и ты влил мою ветку. И что дальше?

кто первее влил тот и прав. второй снова вливает к себе новый мастер и разрешает конфликты

**Comment by russabit** [comment]
> Кстати... public class ExtensionMethods разве он должен быть пабликом?

зависит от твоих предпочтений. почему у тебя такая мысль возникла, объясни логику

**Comment by SkirdaD** [comment]
> > Вот я в этом не сильно понимаю) Смотри, начальная база - это ветка мастер. И я делаю две ветки. Например, мне и Антону. Он что-то пишет и использует, например, переменные активити. А я в своей ветке делаю всё, чтобы убрать эти переменные. И я закончил быстрее, и ты влил мою ветку. И что дальше?
> 
> кто первее влил тот и прав. второй снова вливает к себе новый мастер и разрешает конфликты

А если он влил первый. То я убрав все переменные должен буду поправить его код?
И кто объявляет, что нужно сделать апдейт?

**Comment by SkirdaD** [comment]
> > Кстати... public class ExtensionMethods разве он должен быть пабликом?
> 
> зависит от твоих предпочтений. почему у тебя такая мысль возникла, объясни логику

Ну, это класс для моей активити, которая находится в том же пакете. Никому другому извне я не даю его использовать.

**Comment by russabit** [comment]
> > > Кстати... public class ExtensionMethods разве он должен быть пабликом?
> > 
> > 
> > зависит от твоих предпочтений. почему у тебя такая мысль возникла, объясни логику
> 
> Ну, это класс для моей активити, которая находится в том же пакете. Никому другому извне я не даю его использовать.

так, значит какой модификатор доступа должен быть?

**Comment by russabit** [comment]
> > > Вот я в этом не сильно понимаю) Смотри, начальная база - это ветка мастер. И я делаю две ветки. Например, мне и Антону. Он что-то пишет и использует, например, переменные активити. А я в своей ветке делаю всё, чтобы убрать эти переменные. И я закончил быстрее, и ты влил мою ветку. И что дальше?
> > 
> > 
> > кто первее влил тот и прав. второй снова вливает к себе новый мастер и разрешает конфликты
> 
> А если он влил первый. То я убрав все переменные должен буду поправить его код? И кто объявляет, что нужно сделать апдейт?

тебе сам гитхаб покажет что теперь есть конфликты из-за нового кода, поэтому заставит тебя править сам гитхаб - ПР заблокируется

**Comment by SkirdaD** [comment]
> > > > Кстати... public class ExtensionMethods разве он должен быть пабликом?
> > > 
> > > 
> > > зависит от твоих предпочтений. почему у тебя такая мысль возникла, объясни логику
> > 
> > 
> > Ну, это класс для моей активити, которая находится в том же пакете. Никому другому извне я не даю его использовать.
> 
> так, значит какой модификатор доступа должен быть?

дефолтный

**Comment by russabit** [comment]
> > > > > Кстати... public class ExtensionMethods разве он должен быть пабликом?
> > > > 
> > > > 
> > > > зависит от твоих предпочтений. почему у тебя такая мысль возникла, объясни логику
> > > 
> > > 
> > > Ну, это класс для моей активити, которая находится в том же пакете. Никому другому извне я не даю его использовать.
> > 
> > 
> > так, значит какой модификатор доступа должен быть?
> 
> дефолтный

правильно молодец

**Comment by russabit** [comment]
готово
