### ISSUE TITLE
огранизуем по клину

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#16]
есть такой подход как чистая архитектура (отсюда сокращение - клин). хотел предложить тебе почитать вот [это](https://habr.com/ru/post/269589/), но пробежался быстренько и у меня кровь из глаз начала идти от бездарности переводчика. [Вот](https://habr.com/ru/company/mobileup/blog/335382/) намного лучше статья, я по ней впервые разобрался помню. Тебе надо посидеть подумать что к чему относится - главные разделы это бизнес-логика (Domain - домен/сущности Entities), UI (или слой представления/взаимодействия с пользователем) и Data (не дата, а данные по-русски). Поэтому пока что тут напиши к чему относится каждый класс и по каким папкам рассортировать.

**Comment by SkirdaD** [comment]
Абсолютно все классы должны быть в какой-то папке?

**Comment by SkirdaD** [comment]
Я так понял, что бизнес логика - это часть кода, которая выполняет то, ради чего пишется это приложение.
Поэтому Calculator  - это бизнес логика.
И тут либо больше ничего не относится к БЛ, либо еще И КалькуляторДата.

**Comment by SkirdaD** [comment]
К Data я бы отнес:
- StringKeys
- Operation
- CalculatorData (если моё предположение, что это бизнес логика неверно)

**Comment by SkirdaD** [comment]
К UI я бы отнес:
- MainActivity
- MainActivityHolder
- OnCLFactory
- все ClickListener-ы

**Comment by SkirdaD** [comment]
Остался класс ExtMethods.
Не знаю, вроде к бизнесу он не относится, тк это всё-таки вспомогательный класс.
К UI тоже как-то не подходит.
Но если выбирать между этими двумя, то к UI

**Comment by russabit** [comment]
> Абсолютно все классы должны быть в какой-то папке?

обычно да

**Comment by russabit** [comment]
> Я так понял, что бизнес логика - это часть кода, которая выполняет то, ради чего пишется это приложение. Поэтому Calculator - это бизнес логика. И тут либо больше ничего не относится к БЛ, либо еще И КалькуляторДата.

да, плюс сущности которыми этот калькулятор управляет, значит калькулятордата туда же, правильно. а вот operation почему ты отнёс к данным? они тоже сущности - ими управляет калькулятор, значит по клину они даже главнее калькулятора (более глубокий слой в луковице где БЛ внутри, а все что от неё зависит выше/снаружи), почитай ещё раз статью на хабре

**Comment by russabit** [comment]
> К UI я бы отнес:
> 
> * MainActivity
> * MainActivityHolder
> * OnCLFactory
> * все ClickListener-ы

здесь правильно

**Comment by russabit** [comment]
> Остался класс ExtMethods. Не знаю, вроде к бизнесу он не относится, тк это всё-таки вспомогательный класс. К UI тоже как-то не подходит. Но если выбирать между этими двумя, то к UI

поэтому так важно называть его правильно - я тебе даже предлагал MainActivityExtensions. чтобы понять надо смотреть где он используется

**Comment by russabit** [comment]
вообще под данными имею в виду то, что либо сохраняется как действия пользователя (предыдущие операции), либо например если мы бы сделали игру где с сервера приходят описания задачек. поэтому константы не относятся к данным - мы знаем их значения на этапе написания кода, и они либо относятся к сущностям - операции калькулятора это общеизвестные штуки, либо какие-то константы типа названий переменных - это то, что мы пишем для дальнейшего своего кода

**Comment by russabit** [comment]
а вообще конечно надо бы написать хотя бы ещё один простой экран, тогда как раз будет ещё более понятно что куда относить - добавится ещё половина таких же файлов и вопрос организации встанет сам собой

**Comment by SkirdaD** [comment]
> > Остался класс ExtMethods. Не знаю, вроде к бизнесу он не относится, тк это всё-таки вспомогательный класс. К UI тоже как-то не подходит. Но если выбирать между этими двумя, то к UI
> 
> поэтому так важно называть его правильно - я тебе даже предлагал MainActivityExtensions. чтобы понять надо смотреть где он используется

Они так и называются в студии. Я просто в комменте сократил

**Comment by russabit** [comment]
потом переоткрою если плохо разделишь при добавлении нового экрана )
