### ISSUE TITLE
переносим все КЛ в один класс. Знакомство с MVVM

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#19]
>Кликлистенеры я пока сам не понимаю зависимость или нет и к чему они относятся (к активити из-за того что делают часть работы над вьюхами, но они же как части бизнес-логики

_Originally posted by @russabit in https://github.com/SkirdaD/Calculator/issues/17#issuecomment-1441787088_

В общем проводя логичный последовательный рефакторинг мы обнаруживаем, что в КЛ-рах код более-менее повторяется (ты и сам раньше хотел сделать один метод), поэтому логично его как-то объединить. Можно сделать базовый кликлистенер, но это только усложнит код, добавит лишнюю иерархию наследования, а сами КЛ-ы никуда не денутся. 

Другой способ заключается в отходе от ООП и замене КЛ-ов на соответствующие методы в фабрике. Тогда мы получим то, что в андроиде называется архитектурой MVVM (на уровне слоя UI, это важная оговорка и это любят тоже уточнять на собесах) - фабрика станет вьюмоделью, потому что по сути мы просто выносим часть кода из активити в соответствующую ей вьюмодель (гугл плохо выбрал название, лучше бы она называлась activity(или fragment)LogicHolder - по аналогии с вьюхолдером (который они называют viewBinding хаха, но гугл как раз не очень хорош во всём этом). 

поэтому в нашей архитектуре раз фабрика отвечает за создание зависимостей, давай в ней создадим наш MainActivityLogicHolder и перенесём туда весь код из КЛ-ов

**Comment by SkirdaD** [comment]
Там же тоже будет очень много кода. 
Почему перетаскивание кода в другой класс улучшит структуру?

**Comment by SkirdaD** [comment]
Каждый КЛ станет просто методом. А потом просто КЛ вызывает этот метод?

**Comment by SkirdaD** [comment]
Я не понял ничегошеньки!
Я конечно сделаю коммит, но только потому, что ты этого хочешь)
Я не понимаю, как программа узнает, что делать, если нажатие без setOnClickListener не обработать. Я по крайней мере не знаю.
Я понимаю, что при каком-то условии мой метод исполнится. Но не понимаю, при каком. 
Нажатие же должно быть, а значит и сетонкликлистенер, а значит и что-то, что имплиментирует онсликлистенер.

**Comment by SkirdaD** [comment]
Кажется я понял) Смотри.
Другого я не придумаю)

**Comment by russabit** [comment]
> Каждый КЛ станет просто методом. А потом просто КЛ вызывает этот метод?

да всё так. а часть общего кода из этих методов будет в отдельном методе, поэтому будет легко не дублировать

**Comment by russabit** [comment]
> Я не понял ничегошеньки! Я конечно сделаю коммит, но только потому, что ты этого хочешь) Я не понимаю, как программа узнает, что делать, если нажатие без setOnClickListener не обработать. Я по крайней мере не знаю. Я понимаю, что при каком-то условии мой метод исполнится. Но не понимаю, при каком. Нажатие же должно быть, а значит и сетонкликлистенер, а значит и что-то, что имплиментирует онсликлистенер.

ты же выше написал что это будет просто вызов метода внутри сетОнКЛ. дальше ты себя утопил ))
