### ISSUE TITLE
фича (экран истории)

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#21]
история прошедших операций по калькулятору - список-ресайклер, данные будут храниться в базе данных. переход на экран так же по выпадающей менюшке как и для считалочки

**Comment by russabit** [comment]
сделай пока что минималистичный вариант, в каждом элементе списка только операция и её значение, всё. потом уже можно будет добавить дату, порядковый номер и тп

**Comment by SkirdaD** [comment]
Я правильно понимаю, что сначала калькулятор помещает данные в базу данных, а списокресайклер просто их отображает?

**Comment by SkirdaD** [comment]
Я хочу сделать так:
- верну логику экрана истории, тот что был сверху (давно хотел)
- он сбрасывался по нажатию на равно. Пусть так и будет. И так же по нажатию на равно будет заполняться БД.
- То есть в БД будет храниться строка одного расчета, а не одной операции. Например будет выглядеть один элемент: 5+6+4-10=5

**Comment by SkirdaD** [comment]
В БД будет добавляться тогда после нажатия на "=" либо при закрытии приложения.

**Comment by SkirdaD** [comment]
У меня запарка с БД...
Калькулятор фактически сеттит данные в БД, а экран истории считывает из БД и показывает списком.
Значит сама БД должна быть в мэйнАктивити, раз ее дергают разные фрагменты этой активити?
Я короче открою ПР и скину коммиты. Там ничего не работает, но я запутался и меня надо направить.
Я правильно понимаю, что БД это некое хранилище данных в структурированном виде? И мы просто ее создаем и потом пользуемся (записываем туда или считываем из нее).

Листы пока не делал.

**Comment by russabit** [comment]
> Значит сама БД должна быть в мэйнАктивити, раз ее дергают разные фрагменты этой активити?

если в активити положишь то у тебя при перевороте база грохнется

мы пришли к тому же на чем ты застрял в другом ПР - я тебе несколько раз уже подсказывал и пытался навести, а ты в бандл уходил, попробуем снова: что стоит выше активити и не уничтожается при перевороте?

**Comment by russabit** [comment]
случайно пальцем нажал

**Comment by russabit** [comment]
> Листы пока не делал.

листы это что такое ? А4?

**Comment by SkirdaD** [comment]
> > Листы пока не делал.
> 
> листы это что такое ? А4?

список

**Comment by SkirdaD** [comment]
> > Значит сама БД должна быть в мэйнАктивити, раз ее дергают разные фрагменты этой активити?
> 
> если в активити положишь то у тебя при перевороте база грохнется
> 
> мы пришли к тому же на чем ты застрял в другом ПР - я тебе несколько раз уже подсказывал и пытался навести, а ты в бандл уходил, попробуем снова: что стоит выше активити и не уничтожается при перевороте?

статики

**Comment by SkirdaD** [comment]
> > > Значит сама БД должна быть в мэйнАктивити, раз ее дергают разные фрагменты этой активити?
> > 
> > 
> > если в активити положишь то у тебя при перевороте база грохнется
> > мы пришли к тому же на чем ты застрял в другом ПР - я тебе несколько раз уже подсказывал и пытался навести, а ты в бандл уходил, попробуем снова: что стоит выше активити и не уничтожается при перевороте?
> 
> статики

СТАТИКИ!??

**Comment by russabit** [comment]
> статики

нет

> СТАТИКИ!??

НЕТ!!! статики мы для чего используем? для ресурсов, которые нужны нам все время жизни приложения. для того, что нам известно в компайл тайме. БД - Динамическая штука, и в каждом приложении будет наполнена разными данными. если ты экземпляр бд положишь в статическое поле - оно будет висеть всю жизнь приложения, а раз мы в будущем напишем в настройках отключение БД, то как мы её уберём из статического поля? никак, оно будет проинициализированно и висеть всю жизнь приложения. представь пока что скоуп бд это два фрагмента но не все фрагменты (не активити скоуп) для наглядности, хоть и по сути нам она пока нужна все время жизни приложения - главное чтобы она не уничтожалась с активити

**Comment by SkirdaD** [comment]
Я, наверное, понял. Нам нужно положить базу данных в МэйнАктивитиЛоджикХолдер и передавать её фрагментам, которым захотим.

**Comment by SkirdaD** [comment]
> Я, наверное, понял. Нам нужно положить базу данных в МэйнАктивитиЛоджикХолдер и передавать её фрагментам, которым захотим.

Нет. холдер всё равно создается каждый раз. Посмотрел по дебагеру.
Хотя поля лоджика инициализируются один раз.

**Comment by SkirdaD** [comment]
Нам нужен что-то вроде HistoryDataBaseHolder? 
Там будет всё создано, а фрагменты будут оттуда дергать БД?

**Comment by russabit** [comment]
> Нам нужен что-то вроде HistoryDataBaseHolder? Там будет всё создано, а фрагменты будут оттуда дергать БД?

это и есть твой хелпер который ты написал - не важно как ты его назовёшь. важно где он будет лежать. как называется то, что нужно фрагменту или активити для их работы?

**Comment by SkirdaD** [comment]
> > Нам нужен что-то вроде HistoryDataBaseHolder? Там будет всё создано, а фрагменты будут оттуда дергать БД?
> 
> 
> 
> это и есть твой хелпер который ты написал - не важно как ты его назовёшь. важно где он будет лежать. как называется то, что нужно фрагменту или активити для их работы?

Данные... классы... лэйауты тоже нужны...
