### ISSUE TITLE
(рефакторинг) разделение ответственности

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#3]
много писал про модификаторы доступа, ты их не поправил, но наверное в данном случае это пока не очевидно зачем нужно. сейчас задам то, что должно на примере показать в чём отличие твоего выбранного дефолтного от приватного, и уж тем более протектид.

я просил тебя почитать СОЛИД. нам интересен первый принцип (не трать время на остальные, следующие подтянутся попозже на примерах по ходу дела). Не читай статьи так как чаще всего без нормального конкретного примера там написана дикая чушь (например [эта](https://habr.com/ru/company/productivity_inside/blog/505430/) статья реально с неправильными примерами, [эта](https://habr.com/ru/post/688530/) нормальная, но возьми оттуда только описание и не трать время на примеры (или даже вики ещё лучше))

S - Single Responsibility Principle - принцип единственной ответственности. Каждый класс должен иметь только одну зону ответственности.

у тебя всё написано в одном классе MainActivity. Какая у него ответственность? что он делает? попробуй перечислить ниже в комментах, но главное что противоречит чистоте кода, это то, что он делает ДОФИГА всего. Плюс он 439 строчек, что у любого человека зашедшего в этот класс вызовет недоумение - это первый и самой простой способ определить хороший ли код перед тобой или нет. Представь, что я впервые захожу в этот класс и пытаюсь понять что он делает и для чего нужен. открываю структуру посмотреть из чего он состоит и вижу 7 методов и 40+ полей см скрин ниже (даже в экран не влезло!) и почаще используй сам вкладку structure. 

<img width="392" alt="Screenshot 2023-01-18 at 12 20 53 pm" src="https://user-images.githubusercontent.com/50712640/213057513-6faf1d2f-f2b1-4635-9f4d-54bd59363892.png">

И самый смак в том, что если я напишу другой класс у которого есть ссылка на эту активити, то он видит все её методы (и даже поля! ладно хоть они неизменяемые, иначе и засеттить что-то левое можно было бы) и может сделать какую-нибудь фигню (смотри мой коммит - две строчки сломали то, что должно быть написано так, чтобы не ломалось), потому что **любой неприватный метод - это часть интерфейса класса**, значит что в данном случае метод оперэйт написан так, что подразумевается что его будет использовать кто-то другой в другом классе, т.к. он торчит наружу:

<img width="570" alt="Screenshot 2023-01-18 at 12 22 20 pm" src="https://user-images.githubusercontent.com/50712640/213057676-81a53b44-234f-43b7-bccb-e4491b87f94b.png">

поэтому твоя задача на этот ишью разделить несколько ответственностей MainActivity на отдельные классы, каждый из которых будет делать только что-то одно (по принципу С из солида). Для начала просто перечисли здесь какие ответственности у класса MainActivity и какие нужны другие классы, и какие у них будут интерфейсы, мы их здесь обсудим и тогда уже начнёшь рефакторить

**Comment by SkirdaD** [comment]
> много писал про модификаторы доступа, ты их не поправил, но наверное в данном случае это пока не очевидно зачем нужно. сейчас задам то, что должно на примере показать в чём отличие твоего выбранного дефолтного от приватного, и уж тем более протектид.

Ты мне в итоге написал, что бы я забил до следующего ишью.

**Comment by SkirdaD** [comment]
Не совсем понимаю в этом контексте слово ответственность.

Но, попробую предположить.

Первое, что пришло на ум, это разделить оперэйт на 4 метода, чтоб каждый метод делал что-то одно.
Сам оперэйт, наверное, может быть классом.

Наверное, классом может быть каждая кнопка (кроме цифр, они должны быть все в одном).

Да, и всё. Больше в голову ничего не идет.

**Comment by russabit** [comment]
ладно, давай с другой стороны зайдём. помнишь ты хотел чтобы я так же тебя спросил как я Антона спрашивал как что контретная строчка делает? давай проведём это с твоим МейнАктивити - чтобы покрыть каждую строчку из 440 объедини из в группы комментами типа 
<img width="553" alt="Screenshot 2023-01-19 at 10 24 28 am" src="https://user-images.githubusercontent.com/50712640/213317261-6388b921-2e51-47dc-b820-16d40d6ff847.png">
и 
<img width="749" alt="Screenshot 2023-01-19 at 10 25 36 am" src="https://user-images.githubusercontent.com/50712640/213317380-f2195060-2477-42ee-ba9d-e5a8bfddd993.png">

с методами тем более! напиши подробно кто их может вызвать, где вызываются, какие поля считывают, какие модифицируют и где эти методы вызываются

ты упоминал слово местная (локальная) переменная (внутри метода), так вот это упражнение тебе поможет понять какие поля на самом деле должны быть полями активити - потому что используются в нескольких методах активити, какие можно вынести отдельно, а какие можно наоборот сделать локальными, т.е. перенести внутрь метода в котором они используются.

это будет первым шагом к пониманию как разделять ответственность (то, что делает конкретная сущность, для чего она написана в первую очередь). Например суть SharedPreferences - сохранять настройку при закрытии приложения. Суть Bundle - сохранять в себя значения при перевороте экрана. Суть Активити - давать тебе работать с жизненным циклом приложения (тут посложнее, но главное это ЖЦ). Поэтому метод ::operate так важно во первых было правильно назвать - видишь, что он не отражает что именно он делает, а во вторых непонятно какие параметры он принимает, какие возвращает - он что-то меняет внутри самой активити, но у него нет чёткой цели
