### ISSUE TITLE
улучшение UX

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#5]
у тебя слишком большие числа показываются через E:

![photo_2023-01-18_12-41-40](https://user-images.githubusercontent.com/50712640/213060424-274a12e6-8bc0-40c9-b293-1f8e647a05a1.jpg)

пользователи жалуются что нету округления (пока сделай три числа после запятой, потом добавим кастомную настройку) и Е это всё-таки как-то не красиво, давай это Е замени на читабельное `х 10 ^`, например чтобы то, что в скрине показывало 45 644 х 2.343х10^7 и 1.07 х 10^12 соответсвенно. 

и поставь пробелы между большими разрядами тоже для читаемости, чтобы 45644 показывалось как 45 644

**Comment by SkirdaD** [comment]
Можно закрыть этот ишью? Ведь эти моменты появились в ишью с фичами

**Comment by SkirdaD** [comment]
> Можно закрыть этот ишью? Ведь эти моменты появились в ишью с фичами

??

**Comment by SkirdaD** [comment]
Ты так и не ответил.

**Comment by russabit** [comment]
давай закроем да
