### ISSUE TITLE
избавляемся от сайд эффектов

### ISSUE THREAD

**Issue by russabit** [SkirdaD/Calculator#8]
фундаментальные вещи мы прошли (что такое статики, файнал и области видимости).

теперь надо разобраться с полями у калькулятора. сеттеров и геттеров у них я почему-то не увидел, и они торчат наружу для активити

причём они не просто торчат с правильными значениями, но эти правильные значения появляются только при правильном порядке сеттинга других полей и вызова оперейт.

получается, что чтобы узнать результат тебе надо сначала засеттить ласт оперейшн и вар1 калькулятору, потом вызвать оперейт, хотя у поле резалт у тебя публичное и активити в любой момент может к нему обратиться, без вызова оперейт, и у ней будет некорректный результат.

сайд-эффект - это как раз про это, когда ты вызываешь метод, но метод не принимает и не возвращает значение (как твой  ::operate сейчас, потому что он void и без аргументов), а просто что-то считает и изменяет какие-то поля. поэтому сейчас у тебя код написан так, что ты отдельной строчкой вызываешь `calculator.operate();`, а потом далее где тебе нужен результат ты тащищь `calculator.result`

чтобы понять что делать можешь сначала добавить геттеры/сеттеры, чтобы увидеть какие методы в каких местах считывают поля, а какие в каких модифицируют, но опять же это не обязательно (можно как промежуточная задача), но в целом для закрытия этого ишью тебе надо написать калькулятор без полей вообще, поэтому и геттеров\сеттеров в итоге не будет.

**Comment by SkirdaD** [comment]
Так) Ты тот ишью закрыл, листенеры позже. Значит этот ишью мой основной на данный момент.
Честно говоря, я и сам заметил, когда писал, что хорошо бы возвращать что-то. Например result, но в итоге я так и не сообразил, как обойтись без остальных переменных.

Если метод будет не воид, то возвращать он будет резалт. Я пока так думаю)

Я создал новую ветку. Могу я удалить старые комментарии из кода? Т.к. я думаю, что в этом ишью будут свои другие комменты.

**Comment by SkirdaD** [comment]
Я так понимаю, что раз нужен калькулятор без полей, то оперэйт должен иметь входные данные.

**Comment by SkirdaD** [comment]
Есть сумбурные мысли:
Если я перенесу переменные в главный класс, то это ведь не решение проблемы?) А резалтом будет просто возвращаемое значение самим оперэйт.

**Comment by SkirdaD** [comment]
Так... например, result в листенерах 2 раза сеттится и 1 раз читается. Хотел переделать через сеттеры и геттеры, но не вижу уже смысла, так как сути дела это уже ничего не меняет.

**Comment by russabit** [comment]
думаешь в ту сторону. возьми один листенер и проведи логическую цепочку, какие поля калькулятору ты сеттишь в начале (типа вар1 и вар2 и операцию) до вызова оперейт, и когда достаёшь резалт. то, что ты сеттишь перед вызовом оперейта будет входными аргументами (то, что нужно калькулятору для расчёта результата), то что ты вытаскиваешь после вызова оперейт (резалт и может ещё что-нибудь?) будет возвращаемым значением.

помни о разделении ответственности. задача калькулятора - предоставлять "ручку" за которую активити будет дёргать калькулятор, чтобы получить результат. ручке надо знать лишь о том, какие числа ей передали и какую операцию над ними провести. а задача активити эти числа, операцию и результат подставить во вьюхах чтобы показать пользователю

**Comment by SkirdaD** [comment]
Смотри мой коммит. И смотри только на листенер кнопки плюс.
Я вывел переменные из калькулятора в мэйнактивити. Оперэйт стал возвращать дабл (резалт). И вывел энам в отдельный класс.
В мэйнактивити снова куча переменных и это мне не нравится)

**Comment by SkirdaD** [comment]
Если правильный подход, то следующий шаг хочу сделать весь код в листенерах объединить в метод. И в каждом листенере просто метод с разными входными данными.

**Comment by russabit** [comment]
ладно, я тебя запутал снова и про сайд эффекты пока рановато. полей калькулятора в активити уж тем более не должно быть. тебе скорее всего мешает то, что ты в листенерах обращаешься к этим полям, так? тогда просто перенеси всю логику из листенеров в калькулятор, и там он будет дёргать эти поля раз без них не получается

**Comment by SkirdaD** [comment]
Да, после этого комментария я совсем приуныл)
Хорошо, пока перенесу всё в калькулятор, как было раньше. Может еще что-нибудь сделаю. А там отпишешься.

**Comment by SkirdaD** [comment]
Короче, я всё равно продолжил биться с этой темой... 
Посмотри мой коммит и скажи в ту сторону или нет. 
Но: 
- переменные я уже практически не использую, 
- калькулятор только считает, 
- создал универсальный метод для использования в листенерах.

Пока работает криво, калькулятор не считает)) и  много чего  закомментил, чтоб не мешало компилироваться. 
Мне важно тот ли вектор моих действий?

**Comment by russabit** [comment]
> пока перенесу всё в калькулятор

и добавил поля в активити. Отписался по этому поводу в комментах к коммиту. Здесь напишу в целом.

Вижу что до всего ты сам не дойдёшь, поэтому давай тебе напишу шаги, как архитектурно должно быть реализовано:

активити - считывает с виджетов все значения (твоих любимых "необходимых" полей) - вызывает у калькулятора ::operate, передавая ему все эти значения, и то, что делать в случае ошибки (колбек onError) и получает результат - возвращаемое значение калькулятора (опять все поля которые ты ей передал + результат, либо ошибку - тогда можно без колбэка, будет ещё проще). Всё что получила от калькулятора сеттит в виджеты и показывает. либо показывает ошибку, если она есть. Следующее нажатие на кнопку с новым значением, следующий вызов ::operate, всё то же самое. никакой логики кроме вытаскивания из виджетов данных, вызова оперейт у калькулятора и реакции на результат у активити быть не должно. точка. калькулятор ничего не должен вызывать у активити. точка. это две разные сущности общающиеся между собой через один метод ::оперейт. точка. который вызывается одинаково независимо от того первый ли это раз через равно, или следующие операции. никаких сеттеров и геттеров быть не должно ни у активити (упаси бог!), ни у калькулятора. калькулятор принимает нужные ему данные и отдаёт нужные активити данные после того как посчитал. активити ему эти данные отдала сначала, потом получила результат и проставила их на экране. всё. активити не нужны поля потому что всё будет отдаваться калькулятору и калькулятором же возвращаться. как вернулось, активити проставила новые. 

в чём сложность? не догадался, что резалт после первой операции это и есть var1 при следующей? что оперейт может возвращать не только double, но и что угодно? что одного правильно написанного оперейта достаточно для всего?

твой "грейт" метод - антипаттерн. метод должен делать одну вещь, у тебя же он обрабатывает (по порядку):

- повторное нажатие на то же действие
- показывает ошибку
- сеттит textSecondaryField в зависимости от операции
- сеттит textSecondaryField виджету
- делает какую-то дичь после проверяя нажали ли мы равно (тут даже не понимаю зачем это всё)
- сеттит результат калькулятору (что?? калькулятор считает результат, а тут получается активити посчитала результат - значит эта часть должна быть в калькуляторе)
- вызывает у калькулятора оперейт
- меняет размер текста
и т.п., это я только половину описал. 

должно же быть:
- считать все поля с экрана (в один метод объедини как раз)
- вызвать оперейт у калькулятора и получить результат
- результат передать в метод, который сеттит все поля экрану либо показать ошибку. 

много раз разными способами написал одно и то же. Плюс читай макконелла, вижу что пишешь как раз то, что противоречит его подходам (но это мелочи пока по сравнению с созданием активити в калькуляторе, это дичь полная - ещё и означает что разделение ответственности ты ещё так и не понял).

**Comment by russabit** [comment]
перед написанием кода садись всегда и напиши на листочке какие сущности должны быть, какой API у твоих сущностей (какая ручка за которую дёргать), кто клиент, а кто сервер (кто дёргает чью ручку), кто про что знает (клиент знает про сервер, сервер не знает про клиент), какие данные куда передаются и где нужны, и какая логическая цепочка у твоих операций, на каком этапе может выскочить ошибка где и кто её должен обрабатывать. а потом просто реализуй смотря на свою схему, а не действуй как слепой котёнок дописывая статик там где не работает или создавая новую активити и ручку у человека за которую дёргает молоток и о которой знает. Тут у тебя ещё ни наследования, ни полиморфизма, ничего нету, только абстракция и инкапсуляция - выделение правильных сущностей в классы и правильное взаимодействие между ними чтобы один не ломал другого. всё

**Comment by SkirdaD** [comment]
Размазал меня) Сейчас тогда отпишусь по каждому моменту. Вкратце, логику моей изначальной реализации приложения, наверное, нельзя подогнать под эти моменты. Нужно переписать почти всё)

**Comment by SkirdaD** [comment]
> активити - считывает с виджетов все значения (твоих любимых "необходимых" полей) - вызывает у калькулятора ::operate, передавая ему все эти значения, и то, что делать в случае ошибки (колбек onError) и получает результат - возвращаемое значение калькулятора (опять все поля которые ты ей передал + результат, либо ошибку - тогда можно без колбэка, будет ещё проще). Всё что получила от калькулятора сеттит в виджеты и показывает. либо показывает ошибку, если она есть. Следующее нажатие на кнопку с новым значением, следующий вызов ::operate, всё то же самое. никакой логики кроме вытаскивания из виджетов данных, вызова оперейт у калькулятора и реакции на результат у активити быть не должно. точка.

Конечно, это я понимал. Сначала так и задумывалось. Но потом я упирался в какую-нибудь проблему и начиналась "моя магия"))) Примитивную логику калькулятора у меня получалось таким способом сделать, но потом какой-нибудь нюанс и таким подходом у меня уже не получалось. Отсюда и появлялись всякие левые переменные и блоки ифов. 
Тем более не понимая правильной структуры первый раз я написал, как чувствую, но потом сам себя запутывал и не мог свой код подогнать под правила.

**Comment by SkirdaD** [comment]
> калькулятор ничего не должен вызывать у активити. точка. это две разные сущности общающиеся между собой через один метод ::оперейт. точка. который вызывается одинаково независимо от того первый ли это раз через равно, или следующие операции.

Вот это должно было стать для меня основной идеей изначально. Но к логике приложения я подошел поступательно решая конкретные проблемы (по факту упирания в них). Поэтому мой код разрастался всякими условиями и терял общую структуру.

**Comment by SkirdaD** [comment]
> не догадался, что резалт после первой операции это и есть var1 при следующей?

Конечно догадался, но не понимал, как побороть затирание.

**Comment by SkirdaD** [comment]
> должно же быть:
> 
>     * считать все поля с экрана (в один метод объедини как раз)
> 
>     * вызвать оперейт у калькулятора и получить результат
> 
>     * результат передать в метод, который сеттит все поля экрану либо показать ошибку.

Вот до чего я действительно не догадался и что мне было нужно!!!  Все три пункта я и так понимал. Но не догадался, что их можно разнести по 3 методам.
Сейчас объясню. В твоём представлении первый пункт считывает, а третий сеттит практически одни и те же переменные. А если они в одном методе, то как раз затираются. С чем я и застрял.

И это настолько очевидно, когда ты пишешь. А когда сам, то даже в голову не пришло. А в этом и весь ключ.

**Comment by SkirdaD** [comment]
> о это мелочи пока по сравнению с созданием активити в калькуляторе, это дичь полная - ещё и означает что разделение ответственности ты ещё так и не понял

Не буду оправдываться. Да, дичь. И да, я об этом знал, но не придумал другого варианта передать переменную. Почему то подумал, что возвращать эту переменную будет неправильно. Т.к. считал, что оперэйт должен вернуть резалт и ничего больше.

**Comment by SkirdaD** [comment]
> перед написанием кода садись всегда и напиши на листочке какие сущности должны быть, какой API у твоих сущностей (какая ручка за которую дёргать), кто клиент, а кто сервер (кто дёргает чью ручку), кто про что знает (клиент знает про сервер, сервер не знает про клиент), какие данные куда передаются и где нужны, и какая логическая цепочка у твоих операций, на каком этапе может выскочить ошибка где и кто её должен обрабатывать. а потом просто реализуй смотря на свою схему, а не действуй как слепой котёнок дописывая статик там где не работает или создавая новую активити и ручку у человека за которую дёргает молоток и о которой знает. Тут у тебя ещё ни наследования, ни полиморфизма, ничего нету, только абстракция и инкапсуляция - выделение правильных сущностей в классы и правильное взаимодействие между ними чтобы один не ломал другого. всё

Листочков была куча) Не говорил, думал застыдишь меня, что листочками пользуюсь. Ведь у программиста только ноут и ничего больше)
Вот. Так после старых твоих комментов я понимал кто молоток, а кто рука. Но, наверное, нехватка знаний заставляла писать всякую херню.

Сейчас, вроде, много стало яснее. С меня коммит без дичи. Хотя чуток, думаю, всё равно будет.
И да, где-то в джавераше было, что если ваш метод возвращает кучу разных данных, то у вас плохая архитектура метода и приложения в целом. Что бы удобно использовать метод, он должен возвращать что-то одно (переменную, массив, лист и тп). Поэтому думал, что сеттить кучу значений и возвращать еще большую кучу значений неправильно.

**Comment by SkirdaD** [comment]
**Спасибо.**

**Comment by russabit** [comment]
> Отсюда и появлялись всякие левые переменные и блоки ифов.

на самом деле через такое как раз и надо было пройти чтобы ты увидел, что при малейшем изменений условий плохо написанный код становится просто нереально поддерживать, и особенно другому человеку разобраться в том, что там вообще происходит. я кроме одного первого раза и не запускал твой калькулятор чтобы посмотреть, мы тут как раз обсуждаем чистоту кода и то, как его принято писать на реальной работе - потому что твой первый работающий калькулятор подходит для того, чтобы один раз написать и всё работало, потому что компу пофиг как код написан, главное чтобы по производительности его не расшатывало и ошибок не было. мы же тут обсуждаем то, как писать код чтобы человеку впервые зашедшему в твой проект за 5 минут стало всё понятно как работает твоя программа. у макконелла как раз про это главная мысль, что работа программиста заключается в уменьшении когнитивной (воспринимаемой человеком) сложности - у тебя щас 500 строчек суперзапутанного сложного кода, а надо написать так, чтобы было просто и понятно с первого взгляда где что лежит и кого и когда вызывает и куда что передаёт. а всякие подходы, паттерны и т.п. это просто варианты из возможных уменьшить когнитивную сложность для того, кто твой код будет читать

**Comment by russabit** [comment]
> где-то в джавераше было, что если ваш метод возвращает кучу разных данных, то у вас плохая архитектура метода и приложения в целом. Что бы удобно использовать метод, он должен возвращать что-то одно (переменную, массив, лист и тп). Поэтому думал, что сеттить кучу значений и возвращать еще большую кучу значений неправильно.

да, несколько значений неправильно чтобы метод возвращал (он и не может!). поэтому я и вёл тебя к этому где-то в прошлых обсуждениях, что он и должен возвращать не резалт типа дабл, а какой-нибудь CalculatorData - всё поля и возможную ошибку. Пришлось теперь написать открыто, для этого классы и существуют - чтобы твои 5 полей объеденить одной сущностью - данные, нужные калькулятору. Принцип ооп абстракция, снова
